language: c
compiler:
    - gcc
branches:
  - only:
    - master
    - travis
env:
  matrix:
    - JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
    - sudo apt-get update -qq -y
    - sudo apt-get install julia -y
script:
    - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("Iceberg"))`); Pkg.pin("Iceberg"); Pkg.resolve()'
    - julia ./tests.jl
